# This is a basic workflow to help you get started with Actions

name: scheduled-job

on:
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    - cron: '*/5 * * * *'
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

    - name: Trigger
      run: |
        curl -X POST https://api.github.com/repos/riccardoporreca/gh-actions-test/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token '${{ secrets.GITHUB_TOKEN }}'' \
        --data '{"event_type": "scheduled job"}'
